GMAIL_USERNAME: 'grackergymapp@gmail.com'
GMAIL_PASSWORD: 'arnm dxfo uemz kdgk'
GOOGLE_OAUTH_CLIENT_ID: '390333610328-b0eolgo57f8id99aldls3c1mci0nesha.apps.googleusercontent.com'
GOOGLE_OAUTH_CLIENT_SECRET: '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'
